"""
Extract collision incidents from transcripts.

Two-step pipeline:
  1. Categorize every block by call type (free, regex) — saved to call_log.jsonl
  2. Claude Haiku structured extraction — only on collision-flagged blocks

The call log preserves a record of every processed block (medical, fire, vehicle
collision, mental health, etc.) for context and longitudinal analysis. The
collision-specific incidents get their own incidents JSONL for SWITRS comparison.

Output files per date:
  data/incidents/{city}/{YYYYMMDD}.jsonl       — collision incidents (Claude-extracted)
  data/incidents/{city}/{YYYYMMDD}_call_log.jsonl — all blocks, categorized

Usage:
    python -m broadcastify.extract --city el_cerrito --date 2025-10-01
"""

import json
import re
from collections import Counter
from datetime import date
from pathlib import Path

import anthropic
import click
import yaml

KEYWORDS_FILE = Path("config/keywords.yaml")

SYSTEM_PROMPT = """\
You are extracting structured incident records from EMS/fire dispatch radio transcripts.

The transcripts were auto-generated by Whisper from scanner audio and contain:
- ASR errors and garbled words (radio static, clipped speech)
- Heavy dispatch jargon and abbreviations:
    TC = traffic collision
    MVA = motor vehicle accident
    ped / PV = pedestrian victim
    hitter = hit-and-run driver
    VS = versus (e.g. "vehicle vs bicycle")
    IC = incident command
    BLS/ALS = basic/advanced life support (medical severity)
- Street names that may be mangled

Your task:
1. Read the transcript and identify any dispatched incidents involving vehicles and bicycles or pedestrians.
2. For each such incident, output a JSON object in the array.
3. If no relevant incidents are found, output an empty array [].
4. Do not invent incidents — only extract what is clearly present.

Output ONLY a JSON array of incident objects with these fields:
  incident_type: "traffic_collision" | "bicycle_collision" | "pedestrian_collision" | "hit_and_run" | "other"
  involves_bicycle: true/false
  involves_pedestrian: true/false
  location: string (street, intersection, or block as spoken — correct obvious ASR errors)
  injuries_mentioned: true/false
  cut_off: true/false  (true if the transcript appears to cut off mid-dispatch)
  confidence: 0.0-1.0 (your confidence this is a real collision incident)
  raw_text: string (the relevant portion of the transcript that triggered extraction)
"""


def _load_keywords() -> tuple[dict[str, list[re.Pattern]], list[re.Pattern], list[re.Pattern]]:
    """Load call_type categories, collision patterns, and exclude patterns."""
    data = yaml.safe_load(KEYWORDS_FILE.read_text())

    call_type_patterns: dict[str, list[re.Pattern]] = {}
    for category, patterns in data.get("call_types", {}).items():
        call_type_patterns[category] = [re.compile(p, re.IGNORECASE) for p in patterns]

    collision = [re.compile(p, re.IGNORECASE) for p in data.get("collision", [])]
    exclude = [re.compile(p, re.IGNORECASE) for p in data.get("exclude", [])]
    return call_type_patterns, collision, exclude


def classify_call_type(text: str, call_type_patterns: dict[str, list[re.Pattern]]) -> str:
    """Return the first matching call type category, or 'other'."""
    for category, patterns in call_type_patterns.items():
        for p in patterns:
            if p.search(text):
                return category
    return "other"


def keyword_matches(text: str, collision_patterns, exclude_patterns) -> bool:
    """Return True if text matches any collision keyword but no exclude keywords."""
    for excl in exclude_patterns:
        if excl.search(text):
            return False
    for pattern in collision_patterns:
        if pattern.search(text):
            return True
    return False


def _get_context_tail(prev_transcript: dict | None, seconds: int = 30) -> str:
    """
    Return the last `seconds` of text from the previous block's transcript
    to handle dispatch calls that straddle block boundaries.
    """
    if prev_transcript is None:
        return ""
    segments = prev_transcript.get("segments", [])
    if not segments:
        return ""
    duration = segments[-1].get("end", 0)
    cutoff = max(0, duration - seconds)
    tail_segments = [s["text"] for s in segments if s.get("start", 0) >= cutoff]
    return " ".join(tail_segments).strip()


def _extract_with_claude(
    transcript_text: str,
    block_start_utc: str | None,
    city: str,
    client: anthropic.Anthropic,
) -> list[dict]:
    """Send a flagged transcript to Claude Haiku for structured extraction."""
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": f"Transcript:\n{transcript_text}"}],
    )

    raw = response.content[0].text.strip()

    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

    try:
        incidents = json.loads(raw)
        if not isinstance(incidents, list):
            incidents = [incidents]
    except json.JSONDecodeError:
        return [
            {
                "incident_type": "parse_error",
                "raw_llm_output": raw,
                "block_start_utc": block_start_utc,
                "city": city,
                "confidence": 0.0,
            }
        ]

    for inc in incidents:
        inc["block_start_utc"] = block_start_utc
        inc["city"] = city

    return incidents


def _print_day_summary(
    dt: date,
    city: str,
    call_log: list[dict],
    incidents: list[dict],
) -> None:
    total = len(call_log)
    if total == 0:
        return

    counts = Counter(r["call_type"] for r in call_log)
    flagged = sum(1 for r in call_log if r["collision_flagged"])

    bike = sum(1 for i in incidents if i.get("involves_bicycle"))
    ped = sum(1 for i in incidents if i.get("involves_pedestrian"))
    veh_only = sum(
        1 for i in incidents
        if not i.get("involves_bicycle") and not i.get("involves_pedestrian")
        and i.get("incident_type") != "parse_error"
    )

    click.echo(f"\n  ── {city} {dt} ({'─' * 30}")
    click.echo(f"  {'Blocks processed:':<26} {total}")
    click.echo(f"  {'Call type breakdown:':<26}")
    for call_type, count in sorted(counts.items(), key=lambda x: -x[1]):
        pct = count / total * 100
        click.echo(f"    {call_type:<22} {count:>3}  ({pct:.0f}%)")
    click.echo(f"  {'Collision-flagged:':<26} {flagged}/{total}")
    click.echo(f"  {'Incidents extracted:':<26} {len(incidents)}")
    if incidents:
        click.echo(f"    {'bicycle:':<22} {bike}")
        click.echo(f"    {'pedestrian:':<22} {ped}")
        click.echo(f"    {'vehicle only:':<22} {veh_only}")


def extract_date(
    city: str,
    dt: date,
    data_dir: Path = Path("data"),
    overwrite: bool = False,
) -> tuple[list[dict], list[dict]]:
    """
    Categorize all transcripts and extract collision incidents for a city on a date.
    Returns (incidents, call_log).
    """
    transcript_dir = data_dir / "transcripts" / city / dt.strftime("%Y%m%d")
    if not transcript_dir.exists():
        click.echo(f"No transcripts at {transcript_dir}")
        return [], []

    out_dir = data_dir / "incidents" / city
    out_dir.mkdir(parents=True, exist_ok=True)
    incidents_path = out_dir / f"{dt.strftime('%Y%m%d')}.jsonl"
    call_log_path = out_dir / f"{dt.strftime('%Y%m%d')}_call_log.jsonl"

    if incidents_path.exists() and call_log_path.exists() and not overwrite:
        incidents = [json.loads(l) for l in incidents_path.read_text().splitlines() if l]
        call_log = [json.loads(l) for l in call_log_path.read_text().splitlines() if l]
        return incidents, call_log

    call_type_patterns, collision_patterns, exclude_patterns = _load_keywords()
    client = anthropic.Anthropic()

    transcript_files = sorted(transcript_dir.glob("*.json"))
    if not transcript_files:
        return [], []

    all_incidents: list[dict] = []
    call_log: list[dict] = []
    prev_transcript: dict | None = None
    flagged = 0

    for tf in transcript_files:
        transcript = json.loads(tf.read_text())
        text = transcript.get("text", "")
        block_start_utc = transcript.get("block_start_utc")

        call_type = classify_call_type(text, call_type_patterns)
        is_collision = keyword_matches(text, collision_patterns, exclude_patterns)

        call_log.append({
            "file": transcript.get("file", tf.name),
            "block_start_utc": block_start_utc,
            "city": city,
            "call_type": call_type,
            "collision_flagged": is_collision,
            "text_preview": text[:120].strip(),
        })

        if not is_collision:
            prev_transcript = transcript
            continue

        flagged += 1
        click.echo(f"  [flagged] {tf.name}")

        context = _get_context_tail(prev_transcript)
        full_text = (f"[Context from previous block:] {context}\n\n" + text) if context else text

        incidents = _extract_with_claude(full_text, block_start_utc, city, client)
        all_incidents.extend(incidents)
        prev_transcript = transcript

    click.echo(f"  {flagged}/{len(transcript_files)} blocks flagged → {len(all_incidents)} incidents")

    with incidents_path.open("w") as f:
        for inc in all_incidents:
            f.write(json.dumps(inc, ensure_ascii=False) + "\n")

    with call_log_path.open("w") as f:
        for entry in call_log:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    _print_day_summary(dt, city, call_log, all_incidents)

    return all_incidents, call_log


@click.command()
@click.option("--city", required=True)
@click.option("--date", "date_str", required=True, help="YYYY-MM-DD")
@click.option("--overwrite", is_flag=True, default=False)
@click.option("--data-dir", default="data", show_default=True)
def main(city, date_str, overwrite, data_dir):
    """Extract collision incidents from transcripts for a city and date."""
    dt = date.fromisoformat(date_str)
    incidents, call_log = extract_date(city, dt, data_dir=Path(data_dir), overwrite=overwrite)
    click.echo(f"\nDone. {len(incidents)} incidents extracted.")


if __name__ == "__main__":
    main()
