"""
Extract collision incidents from transcripts.

Two-step pipeline:
  1. Keyword filter (free, regex) — flags ~5-10% of blocks as potentially relevant
  2. Claude Haiku structured extraction — only on flagged blocks

The LLM step corrects dispatch jargon transcription errors (TC, MVA, ped, hitter)
and extracts structured incident records. This is what turns messy scanner text
into data comparable against SWITRS.

Block boundary handling: when processing block N, the last 30 seconds of block N-1
are prepended as context, since a dispatch call can straddle the 30-minute boundary.

Usage:
    python -m broadcastify.extract --city el_cerrito --date 2025-10-01
"""

import json
import re
from datetime import date
from pathlib import Path
from typing import Any

import anthropic
import click
import yaml

KEYWORDS_FILE = Path("config/keywords.yaml")

SYSTEM_PROMPT = """\
You are extracting structured incident records from EMS/fire dispatch radio transcripts.

The transcripts were auto-generated by Whisper from scanner audio and contain:
- ASR errors and garbled words (radio static, clipped speech)
- Heavy dispatch jargon and abbreviations:
    TC = traffic collision
    MVA = motor vehicle accident
    ped / PV = pedestrian victim
    hitter = hit-and-run driver
    VS = versus (e.g. "vehicle vs bicycle")
    IC = incident command
    BLS/ALS = basic/advanced life support (medical severity)
- Street names that may be mangled

Your task:
1. Read the transcript and identify any dispatched incidents involving vehicles and bicycles or pedestrians.
2. For each such incident, output a JSON object in the array.
3. If no relevant incidents are found, output an empty array [].
4. Do not invent incidents — only extract what is clearly present.

Output ONLY a JSON array of incident objects with these fields:
  incident_type: "traffic_collision" | "bicycle_collision" | "pedestrian_collision" | "hit_and_run" | "other"
  involves_bicycle: true/false
  involves_pedestrian: true/false
  location: string (street, intersection, or block as spoken — correct obvious ASR errors)
  injuries_mentioned: true/false
  cut_off: true/false  (true if the transcript appears to cut off mid-dispatch)
  confidence: 0.0-1.0 (your confidence this is a real collision incident)
  raw_text: string (the relevant portion of the transcript that triggered extraction)
"""


def _load_keywords() -> tuple[list[re.Pattern], list[re.Pattern]]:
    """Load collision and exclude keyword patterns."""
    data = yaml.safe_load(KEYWORDS_FILE.read_text())
    collision = [re.compile(p, re.IGNORECASE) for p in data.get("collision", [])]
    exclude = [re.compile(p, re.IGNORECASE) for p in data.get("exclude", [])]
    return collision, exclude


def keyword_matches(text: str, collision_patterns, exclude_patterns) -> bool:
    """Return True if text matches any collision keyword but no exclude keywords."""
    for excl in exclude_patterns:
        if excl.search(text):
            return False
    for pattern in collision_patterns:
        if pattern.search(text):
            return True
    return False


def _get_context_tail(prev_transcript: dict | None, seconds: int = 30) -> str:
    """
    Return the last `seconds` of text from the previous block's transcript
    to handle dispatch calls that straddle block boundaries.
    """
    if prev_transcript is None:
        return ""
    segments = prev_transcript.get("segments", [])
    if not segments:
        return ""
    duration = segments[-1].get("end", 0)
    cutoff = max(0, duration - seconds)
    tail_segments = [s["text"] for s in segments if s.get("start", 0) >= cutoff]
    return " ".join(tail_segments).strip()


def _extract_with_claude(
    transcript_text: str,
    block_start_utc: str | None,
    city: str,
    client: anthropic.Anthropic,
) -> list[dict]:
    """Send a flagged transcript to Claude Haiku for structured extraction."""
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Transcript:\n{transcript_text}",
            }
        ],
    )

    raw = response.content[0].text.strip()

    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

    try:
        incidents = json.loads(raw)
        if not isinstance(incidents, list):
            incidents = [incidents]
    except json.JSONDecodeError:
        # Extraction failed — save raw for debugging
        return [
            {
                "incident_type": "parse_error",
                "raw_llm_output": raw,
                "block_start_utc": block_start_utc,
                "city": city,
                "confidence": 0.0,
            }
        ]

    for inc in incidents:
        inc["block_start_utc"] = block_start_utc
        inc["city"] = city

    return incidents


def extract_date(
    city: str,
    dt: date,
    data_dir: Path = Path("data"),
    overwrite: bool = False,
) -> list[dict]:
    """
    Run extraction on all transcripts for a city on a given date.
    Returns list of incident records.
    """
    transcript_dir = data_dir / "transcripts" / city / dt.strftime("%Y%m%d")
    if not transcript_dir.exists():
        click.echo(f"No transcripts at {transcript_dir}")
        return []

    out_dir = data_dir / "incidents" / city
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{dt.strftime('%Y%m%d')}.jsonl"

    if out_path.exists() and not overwrite:
        # Load existing
        return [json.loads(line) for line in out_path.read_text().splitlines() if line]

    collision_patterns, exclude_patterns = _load_keywords()
    client = anthropic.Anthropic()

    transcript_files = sorted(transcript_dir.glob("*.json"))
    if not transcript_files:
        return []

    all_incidents: list[dict] = []
    prev_transcript: dict | None = None
    flagged = 0

    for tf in transcript_files:
        transcript = json.loads(tf.read_text())
        text = transcript.get("text", "")

        if not keyword_matches(text, collision_patterns, exclude_patterns):
            prev_transcript = transcript
            continue

        flagged += 1
        click.echo(f"  [flagged] {tf.name}")

        # Prepend tail of previous block for boundary context
        context = _get_context_tail(prev_transcript)
        full_text = (f"[Context from previous block:] {context}\n\n" + text) if context else text

        incidents = _extract_with_claude(
            full_text,
            transcript.get("block_start_utc"),
            city,
            client,
        )
        all_incidents.extend(incidents)
        prev_transcript = transcript

    click.echo(f"  {flagged}/{len(transcript_files)} blocks flagged → {len(all_incidents)} incidents")

    # Write JSONL output
    with out_path.open("w") as f:
        for inc in all_incidents:
            f.write(json.dumps(inc, ensure_ascii=False) + "\n")

    return all_incidents


@click.command()
@click.option("--city", required=True)
@click.option("--date", "date_str", required=True, help="YYYY-MM-DD")
@click.option("--overwrite", is_flag=True, default=False)
@click.option("--data-dir", default="data", show_default=True)
def main(city, date_str, overwrite, data_dir):
    """Extract collision incidents from transcripts for a city and date."""
    dt = date.fromisoformat(date_str)
    incidents = extract_date(city, dt, data_dir=Path(data_dir), overwrite=overwrite)
    click.echo(f"\nDone. {len(incidents)} incidents extracted.")


if __name__ == "__main__":
    main()
